### ISSUE TITLE
Add function to build catalogues

### ISSUE THREAD

**Issue by baezortega** [kgori/sigfit#10]
Incorporate user function to construct the input mutational catalogues from a table with Chrom, Pos, Ref and Alt. We will need to include an extra package like BSgenome.Hsapiens.UCSC.hg19. We should also include the option of using a different genome from a FASTA file (as in SomaticSignatures).

**Comment by baezortega** [comment]
Working on this now.

**Comment by kgori** [comment]
Is it possible to do this without adding BSgenome? I'd like to avoid having Bioconductor as a dependency?

**Comment by baezortega** [comment]
Sure, I'll look into it. I've removed the BSgenome dependency already.

**Comment by baezortega** [comment]
I haven't found any package that is able to load a whole genome FASTA in a reasonable time and is not part of Bioconductor (although there's surely a way). So far I've made the function so that the user needs to provide a table with REF base, ALT base and trinucleotide context. We can suggest how to obtain the trinucleotide context in the vignettes, or add this later on.
