### ISSUE TITLE
Revise log_lik in emu models

### ISSUE THREAD

**Issue by baezortega** [kgori/sigfit#17]
The log likelihood code in sigfit_ext_emu.stan so far generated a matrix instead of a vector:

```
model {
    ...
    // Likelihood
    for (g in 1:G) {
        counts[g] ~ poisson(sig_expo_opps[g]);
    }
}
generated quantities {
    matrix[G, C] log_lik;
    for (g in 1:G) {
        for (c in 1:C) {
            log_lik[g, c] = poisson_lpmf(counts[g, c] | sig_expo_opps[g, c]);
        }
    }
}
```

Since the Poisson likelihood is in a vectorised form, I have tried making the log likelihood also vectorised (analogous to that in the nmf models). Although I can't see any problems with this, it needs to be tested.

```
model {
    ...
    // Likelihood
    for (g in 1:G) {
        counts[g] ~ poisson(sig_expo_opps[g]);
    }
}
generated quantities {
    vector[G] log_lik;
    for (g in 1:G) {
        log_lik[g] = poisson_lpmf(counts[g] | sig_expo_opps[g]);
    }
}
```

**Comment by kgori** [comment]
The vector needs to be G*C long to fit in all the values. I've fixed this but it's not merged in to master yet.

**Comment by kgori** [comment]
This is merged now.
