### ISSUE TITLE
Keep an eye on Stan error

### ISSUE THREAD

**Issue by baezortega** [kgori/sigfit#19]
The following error message has started to appear when sampling in all Stan models. It doesn't always appear.
```
> nmf.extract = extract_signatures(counts=samples, nsignatures=wtsi.N, method="nmf",
+                                  iter=20000, warmup=5000, seed=999)
Stan sampling:
Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
  no valid constructor available for the argument list
trying deprecated constructor; please alert package maintainer
```
Many users are finding the same problem; apparently the error does not have any effect on the results and will be solved in the next Stan release: https://github.com/stan-dev/rstanarm/issues/202

We should check if this gets solved in the near future.

**Comment by kgori** [comment]
This fix suggested in the Stan discourse (http://discourse.mc-stan.org/t/error-in-new-cppobject-xp/2096)

Change file "tools/make_cpp.R", line 34 from 

    constructors = list(c("SEXP", "SEXP")), fields = character(),

to

    constructors = list(c("SEXP", "SEXP", "SEXP")), fields = character(),

I'll check if it works.

**Comment by baezortega** [comment]
I tried it some time ago and it didn't help.

**Comment by kgori** [comment]
Seems to work for me, after regenerating the C++ files and recompiling.

**Comment by kgori** [comment]
Having not seen the error message when running any recent builds, I'm closing this issue.
