### ISSUE TITLE
Exposures are mislabelled in plot_reconstruction

### ISSUE THREAD

**Issue by kgori** [kgori/sigfit#21]
The signature names don't match up with the correct exposures in ```plot_reconstruction```. The current version of the vignette shows examples. A similar thing happen in ```plot_exposures```.

**Comment by baezortega** [comment]
Silly mistake, thank you for pointing it out! Should be fixed now.

I've also finished the new plot_exposures (which likes being plotted to a huge PDF as well), so I've temporarily switched off the vignette chunks where the old plot_exposures was being used.

**Comment by kgori** [comment]
OK. I've retired the old plot_exposures and deprecated the ggplot version.
