### ISSUE TITLE
Implement optional multi-chain extraction

### ISSUE THREAD

**Issue by baezortega** [kgori/sigfit#23]
Complete the implementation of multi-chain extraction by:

Adding a variable 'chains' set by default to 1 and passed on to rstan::sampling
Adding a parameter 'init' (list, default =NULL ) in extract_signatures(), such that, if provided, the number of chains will be equal to the length of 'init'.

**Comment by baezortega** [comment]
@kgori I think you implemented something along these lines in the paper branch?

**Comment by kgori** [comment]
Yes, I added the same thing. (From memory, so could be wrong) we don't need
to add anything for 'init', it's already a keyword argument in
rstan::sampling, so it will pass through "...".

**Comment by baezortega** [comment]
Then I guess I'll close this (we still need a vignette).
