### ISSUE TITLE
Out of date code in vignette

### ISSUE THREAD

**Issue by dg13** [kgori/sigfit#26]
Hi,
Probably a minor issue, but I get the following error when trying to work through the example in the 
vignette:

exposures <- retrieve_pars(mcmc_samples_fit, 
                           par = "exposures", 
                           hpd_prob = 0.90)

Error in retrieve_pars(mcmc_samples_fit, par = "exposures", hpd_prob = 0.9) : 
  unused argument (par = "exposures")

Looking at the retrieve_pars function, it looks like there's no par option:

function (mcmc_samples, feature, hpd_prob = 0.95, counts = NULL, 
    signatures = NULL, opportunities = NULL, signature_names = NULL) 

packageVersion("sigfit")
[1] ‘1.0.0’
platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          4.3                         
year           2017                        
month          11                          
day            30                          
svn rev        73796                       
language       R                           
version.string R version 3.4.3 (2017-11-30)
nickname       Kite-Eating Tree

**Comment by baezortega** [comment]
I think it's because the vignette refers to the dev version and not to
release 1.0.

**Comment by dg13** [comment]
OK - do the installation instructions in the vignette install by default 1.0? Anyway, just a minor point, thought it would be useful to post here for reference

**Comment by baezortega** [comment]
I think the vignette installs master. It's just a matter of making a new
release.

**Comment by dg13** [comment]
So is it useful to post these comments on the vignette? Or should I delete?

**Comment by kgori** [comment]
Thanks for letting us know about this. It looks like you have the vignette that goes with the dev branch of the code, but are running the master branch (1.0) version, so there is a mismatch in the function signature.
Are you working from the locally-installed vignette that was built when you installed v1.0? If so, then our build script is producing the wrong vignette, which we need to fix. Otherwise, [this vignette](https://github.com/kgori/sigfit/blob/master/vignettes/sigfit_vignette.Rmd) goes with v1.0.

**Comment by kgori** [comment]
Hi. The vignette link in README.md was pointing to the dev branch. I've changed it to point to the version 1.0 release vignette. Sorry for the confusion. The examples in this vignette will work with the release version of sigfit.

**Comment by baezortega** [comment]
Hi,
Sorry for not replying properly before. Alternatively, you could try
installing the dev version, which is more usable and has a more complete
vignette than v1.0.0. You would have to repeat the devtools install
command, adding the argument: ref="dev". Then you should be able to follow
the vignette you were referring to.
Cheers

**Comment by dg13** [comment]
No problem, thanks for the help!
