### ISSUE TITLE
Other out of date code in vignette

### ISSUE THREAD

**Issue by dg13** [kgori/sigfit#27]
In the vignette I found that this code (copied from the vignette):

sigfit::plot_reconstruction(mcmc_samples = mcmc_samples_fit,
                            pdf_path = NULL)

throws this error:

Error in to_matrix(counts) : 
  argument "counts" is missing, with no default

**Comment by kgori** [comment]
Hi. I responded to your other issue (#26). This looks like part of the same issue, so I'm going to close this and leave the other one open.
