### ISSUE TITLE
citation

### ISSUE THREAD

**Issue by arpoe** [kgori/sigfit#31]
Hi, I have used parts of the package (which is excellent, by the way!) and would like to cite it appropriately for publication. I could not find any instructions on this and would like to ask you to let me know how you would like to be cited. Thanks!

**Comment by baezortega** [comment]
Hi Anna, I'm glad that you find the package useful, and thanks for the kind words. It's always nice to discover new users!

We have a preprint in the oven that will be out in 4 weeks, so if that sounds like a good time frame you could cite it. It will be:

Kevin C Gori, Adrian Baez-Ortega. sigfit: flexible Bayesian inference of mutational signatures. _bioRxiv_ (2018).

I'll write here again to update the citation once we get a DOI.

Best, 
Adrian

**Comment by baezortega** [comment]
Hi Anna,

Our preprint is already out! https://www.biorxiv.org/content/early/2018/07/20/372896

The citation is as follows.

Kevin Gori, Adrian Baez-Ortega. sigfit: flexible Bayesian inference of mutational signatures. _bioRxiv_ (2018). doi: 10.1101/372896.
