### ISSUE TITLE
`multiplier` prior in EMu model

### ISSUE THREAD

**Issue by baezortega** [kgori/sigfit#39]
In the model section of the [sigfit_fit_emu.stan](https://github.com/kgori/sigfit/blob/master/exec/sigfit_fit_emu.stan), the prior for the multiplier (real array of size G) is defined inside the for loop, but without indexing. I guess we have to add the index `[i]`, but I don't know if this prior definition is already vectorised. (I'm just wondering if `multiplier` and `exposures` would admit vectorised prior definitions here.)

```
model {
    for (i in 1:G) {
        // Priors
        exposures[i] ~ dirichlet(kappa);
        multiplier ~ cauchy(0, 1);   ###  multiplier[i] ~ cauchy(0, 1); ??

        // Likelihood
        counts[i] ~ poisson(expected_counts[i]);
    }
}
```

**Comment by kgori** [comment]
That's a mistake. It should be multiplier[i] ~ Cauchy if done inside the
loop, or multiplier ~ Cauchy, once, outside the loop. Probably the second
is more efficient. counts and exposures are correct as they are.

**Comment by baezortega** [comment]
That's what I thought. I realised exposures are already vectorised! I'll
fix this in dev.
