### ISSUE TITLE
Implement alpha parameter in EMu fitting model

### ISSUE THREAD

**Issue by baezortega** [kgori/sigfit#4]
Implement Poisson model for fitting – if this is going to be useful. In that case, make an argument for the fit_signatures() function called “model”, which can be “nmf” or “emu” – or alternatively, “multinomial” or “poisson”. We could use opportunities for this Poisson fitting, just as in the extraction.

**Comment by baezortega** [comment]
Seems the model is already done in sigfit_emu_fixed.stan(?).
Just need to add the "model" argument to fit_signatures(), rename sigfit_fit.stan to sigfit_fit_nmf.stan, and rename sigfit_emu_fixed.stan to sigfit_fit_emu.stan.

**Comment by baezortega** [comment]
Implemented, but needs testing.
A user-defined prior ("alpha" argument) needs to be implemented in sigfit_fit_emu.stan, similar to the one in sigfit_fit_nmf.stan (currently, it follows a Cauchy distribution).

**Comment by kgori** [comment]
There's no need for "alpha" in the EMu model. We use alpha to set the Dirichlet prior in the NMF model, but there is no Dirichlet in the EMu model.

**Comment by baezortega** [comment]
But shouldn't there be a way to specify a prior for the exposures in the EMu model?

**Comment by kgori** [comment]
What prior would you want to put on the exposures? It's implicitly uniform as it stands. We could put on an asymmetric prior using a Dirichlet and a positive multiplier (say from a Cauchy or a Gamma).
