### ISSUE TITLE
Fail to install sigfit in Anaconda enviroment on CentOS 7

### ISSUE THREAD

**Issue by WuyangFF95** [kgori/sigfit#47]
Hi @kgori ,

I cannot install the latest version of sigfit through `devtools::install_github("kgori/sigfit")`. Before installing sigfit, I already installed rstan v2.18.2.

The error appears as follows:

> Modules.cpp:203:1:   required from here
> /home/wuyang/bin/anaconda3/lib/R/library/RcppEigen/include/Eigen/src/Core/DenseCoeffsBase.h:650:34: warning: ignoring attributes on template argument 'Eigen::internal::packet_traits<double>::type {aka __vector(2) double}' [-Wignored-attribute ]
>    return internal::first_aligned<int(unpacket_traits<DefaultPacketType>::alignment),Derived>(m);
>                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 -shared -L/home/wuyang/bin/anaconda3/lib/R/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/wuyang/bin/anaconda3/lib -Wl,-rpath-link,/home/wuyang/bin/anaconda3/lib -L/home/wuyang/bin/anaconda3/lib -Wl,-rpath-link,/home/wuyang/bin/anaconda3/lib -o sigfit.so Modules.o -L/home/wuyang/bin/anaconda3/lib/R/lib -lR
> installing to /home/wuyang/bin/anaconda3/lib/R/library/00LOCK-sigfit/00new/sigfit/libs
> ** R
> ** data
> ** exec
> ** inst
> ** byte-compile and prepare package for lazy loading
> ** help
> No man pages found in package  ‘sigfit’ 
> *** installing help indices
> ** building package indices
> ** installing vignettes
> ** testing if installed package can be loaded from temporary location
> ** checking absolute paths in shared objects and dynamic libraries
> ** testing if installed package can be loaded from final location
> ** testing if installed package keeps a record of temporary installation path
> ERROR: hard-coded installation path: please report to the package maintainer and use ‘--no-staged-install’
> * removing ‘/home/wuyang/bin/anaconda3/lib/R/library/sigfit’
> Error: Failed to install 'sigfit' from GitHub:
>   (converted from warning) installation of package ‘/tmp/Rtmpw7FiWm/file225364d8e6069/sigfit_1.3.1.tar.gz’ had non-zero exit status
> 

I also tried the workaround in #46 (Installtion Problem in MacOS), but it didn't work.

> > pkgbuild::compile_dll(path = ".")
> Registered S3 methods overwritten by 'ggplot2':
>   method         from 
>   [.quosures     rlang
>   c.quosures     rlang
>   print.quosures rlang
> Re-compiling sigfit
> ─  installing *source* package ‘sigfit’ ... (524ms)
>    ** using staged installation
>    Registered S3 methods overwritten by 'ggplot2':
>      method         from 
>      [.quosures     rlang
>      c.quosures     rlang
>      print.quosures rlang
>    Wrote C++ file "src/sigfit_ext_emuModule.cc"
>    Wrote C++ file "src/sigfit_ext_nmfModule.cc"
>    Wrote C++ file "src/sigfit_fit_emuModule.cc"
>    Wrote C++ file "src/sigfit_fit_nmfModule.cc"
>    Wrote C++ file "src/sigfit_fit_nmf_hier2Module.cc"
>    Wrote C++ file "src/sigfit_fitex_emuModule.cc"
>    $sigfit_ext_emu
>    NULL
>    
>    $sigfit_ext_nmf
>    NULL
>    
>    $sigfit_fit_emu
>    NULL
>    
>    $sigfit_fit_nmf
>    NULL
>    
>    $sigfit_fit_nmf_hier2
>    NULL
>    
>    $sigfit_fitex_emu
>    NULL
>    
>    $sigfit_fitex_nmf
>    NULL
>    
>    Wrote C++ file "src/sigfit_fitex_nmfModule.cc"
>    Writing NAMESPACE
>    Loading sigfit
>    Loading required package: Rcpp
>    Registered S3 methods overwritten by 'ggplot2':
>      method         from 
>      [.quosures     rlang
>      c.quosures     rlang
>      print.quosures rlang
>    Error in getDLLRegisteredRoutines.DLLInfo(dll, addNames = FALSE) : 
>      must specify DLL via a “DLLInfo” object. See getLoadedDLLs()
>    Calls: <Anonymous> ... assignNativeRoutines -> getDLLRegisteredRoutines.DLLInfo
>    In addition: Warning message:
>    roxygen2 requires Encoding: UTF-8 
>    Execution halted
>    ** libs
>    g++ -std=gnu++14 -I"/home/wuyang/bin/anaconda3/lib/R/include" -DNDEBUG -I"`"/home/wuyang/bin/anaconda3/lib/R/bin/Rscript" --vanilla -e "cat(system.file('include', 'src', package = 'StanHeaders'))"`" -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DEIGEN_NO_DEBUG -I"/home/wuyang/bin/anaconda3/lib/R/library/StanHeaders/include" -I"/home/wuyang/bin/anaconda3/lib/R/library/rstan/include" -I"/home/wuyang/bin/anaconda3/lib/R/library/BH/include" -I"/home/wuyang/bin/anaconda3/lib/R/library/Rcpp/include" -I"/home/wuyang/bin/anaconda3/lib/R/library/RcppEigen/include" -DNDEBUG -D_FORTIFY_SOURCE=2 -O2  -I/home/wuyang/bin/anaconda3/include -Wl,-rpath-link,/home/wuyang/bin/anaconda3/lib  -fpic  -O3 -march=native -mtune=native -fPIC -c Modules.cpp -o Modules.o
>    g++: error: unrecognized command line option ‘-std=gnu++14’
>    make: *** [/home/wuyang/bin/anaconda3/lib/R/etc/Makeconf:175: Modules.o] Error 1
>    ERROR: compilation failed for package ‘sigfit’
> ─  removing ‘/tmp/Rtmpeq7gqF/devtools_install_230246a2fa22c/sigfit’
> Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
>   System command error

I'm just wondering whether it is the same error as the issue in #46 ? Can you tell me how to fix it, or I just have to wait for the next release? Thanks!

**Comment by kgori** [comment]
Hi,

Sorry you've run into this problem. I've released version 1.3.2 to fix this issue.

To install the new version and build the vignettes, run

```r
devtools::install_github("kgori/sigfit", ref = "v1.3.2",
                         build_opts = c("--no-resave-data", "--no-manual"))
```

If you don't want the vignettes, run

```r
devtools::install_github("kgori/sigfit", ref = "v1.3.2")
```

Remember to make sure your conda environment has a C++14-capable compiler.

Kevin

**Comment by WuyangFF95** [comment]
Sorry Kevin,

I'm installing anaconda on an old CentOS system whose gcc compiler is too old to fit for CXX14, and I don't have the root access to update the gcc to >4.9.X. 

From https://stackoverflow.com/questions/31965413/compile-c14-code-with-g, I knew that I can change the flag from `-std=c++14` to `-std=c++1y` solve this error. But how can I change the gcc behavior? Do I need to change it in `sigfit/src/Makevars`. or in other places?

**Comment by WuyangFF95** [comment]
Can I do a workaround in ~/.R/Makevars file? (hinted by https://github.com/stan-dev/rstan/issues/589)

> CXX14FLAGS=-O3 -march=native -mtune=native -fPIC
> CXX14=g++ -std=c++11
> CXX14FLAGS+= -std=c++11
> CXX14STD='-std=c++11'

**Comment by kgori** [comment]
Hi,

You can check the c++14 flags your R is set up to use by looking in the `Makeconf` file in your R installation directory (on my system it's here: `/software/R-latest/lib64/R/etc/Makeconf`). In my case, all the CXX14 entries in `Makeconf` are blank, so I supply my own in `~/.R/Makevars`, based on the CXX11 entries:

    # ~/.R/Makevars
    CXX14 = g++
    CXX14FLAGS = -g -O2
    CXX14PICFLAGS = -fpic
    CXX14STD = -std=gnu++14

This works for me with gcc-6. For your gcc-4 you may have to use `CXX14STD = -std=c++1y` to enable c++14.

One other thing, if you run into any errors coming from `rstantools`, then you need to update to version 2.0.0.9000, with `devtools::install_github("stan-dev/rstantools")`.

Kevin

**Comment by WuyangFF95** [comment]
Thanks Kevin! I'll close this issue now.

**Comment by kimin0402** [comment]
Hi @WuyangFF95 , I'm facing a similar problem right now. Did you solve this issue by changing `~/.R/Makevars?`
