### ISSUE TITLE
install sigfit:  Pandoc is required to build R Markdown vignettes but not available.

### ISSUE THREAD

**Issue by jingydz** [kgori/sigfit#61]
> devtools::install_github("kgori/sigfit", build_vignettes = TRUE,
                         build_opts = c("--no-resave-data", "--no-manual"))
Downloading GitHub repo kgori/sigfit@HEAD
✔  checking for file ‘/tmp/RtmpxrboeS/remotes336b231489cc/kgori-sigfit-46e89a1/DESCRIPTION’ ...
─  preparing ‘sigfit’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  installing the package to build vignettes
E  creating vignettes (3m 7.4s)
   --- re-building ‘sigfit_vignette.Rmd’ using rmarkdown
   Error: processing vignette 'sigfit_vignette.Rmd' failed with diagnostics:
   Pandoc is required to build R Markdown vignettes but not available. Please make sure it is installed.
   --- failed re-building ‘sigfit_vignette.Rmd’

   SUMMARY: processing the following file failed:
     ‘sigfit_vignette.Rmd’

   Error: Vignette re-building failed.
   Execution halted
Error: Failed to install 'sigfit' from GitHub:
  System command 'R' failed, exit status: 1, stdout & stderr were printed

**Comment by baezortega** [comment]
Hello, you should be able to install pandoc with
`sudo apt-get install pandoc`
