### ISSUE TITLE
fit_signatures and genomes-indepedent cosmic reference

### ISSUE THREAD

**Issue by gevro** [kgori/sigfit#64]
Hi,
I'm trying to fit_signatures with mutation counts from a very large targeted panel of the human genome. I calculated the mutation_opportunities for the target panel regions. I then gave that to the fit_signatures 'opportunities' parameter.

I also converted cosmic to genome-independent, and gave that to the fit_signatures 'signatures' parameter:
cosmic_signatures_v3.2_genomeindependent <- convert_signatures(cosmic_signatures_v3.2, opportunities_from="human-genome")

However, this does not detect SBS1, which is clearly visible in the data.
When I view the genome-independent cosmic signature with plot_spectrum(cosmic_signatures_v3.2_genomeindependent,pdf_path="output.pdf"), it looks like many of the signatures have the SBS1-like spectrum. See attached, for example SBS5, SBS6, SBS9, ... 
This is because [ACTG]CG are very low frequency in the human genome, so converting COSMIC to genome-independent form artificially inflates those peaks for many signatures. And then many signatures look like SBS1, and fit_signatures doesn't detect SBS1.

I'm not sure what I'm doing wrong, but based on documentation, I'm pretty sure I'm following the correct process. For example, this is the process you describe in these posts: https://github.com/kgori/sigfit/issues/58 , https://github.com/kgori/sigfit/issues/56

Is it wrong to convert COSMIC signatures to genome-independent when applying to a large targeted human genome panel? But then correcting my mutation counts by our observed mutation_opportunities wouldn't make sense to do.

[blah.pdf](https://github.com/kgori/sigfit/files/8695455/blah.pdf)

**Comment by baezortega** [comment]
You are correct: many COSMIC signatures contain a small fraction of SBS1, which becomes visible when you transform the signatures to a genome-independent format. I would recommend either that you take the opposite approach and transform your mutation counts to a whole-genome-relative format, or that you use a new set of opportunities, calculated as the ratio between your current opportunities and the whole-genome opportunities (`sigfit:::build_opps_matrix(1, 96, "human-genome")`). In either case you would need to fit the original COSMIC signatures without transformation.

Best,
Adrian

**Comment by gevro** [comment]
Thanks. Two more questions for this: "use a new set of opportunities, calculated as the ratio between your current opportunities and the whole-genome opportunities"

1) Just confirming that I would input into fit_signatures opportunities = [sample opportunities] divided by [genome opportunities], and NOT [genome opportunities] divided [sample opportunities] ?

2) Can I use the function human_trinuc_freqs() to get the human genome opportunities? That seems to work too.

Note regarding your other option: "transform your mutation counts to a whole-genome-relative format". I think that is not as good as the above option, if the total mutation count is not normalized back to the original total mutation count, because changes in total mutation count I saw can change the hpd intervals

**Comment by baezortega** [comment]
Hi, I think you are correct on both points.
Adrian
